name: "CHANGELOG Slack Notifier"
description: "Post your CHANGELOG to Slack"
inputs:
  title:
    description: "Message title"
    required: true
  version:
    description: "The CHANGELOG version entry to use"
    required: true
  changelog-file-path:
    description: "The path to the CHANGELOG file"
    required: true
  slack-token:
    description: "Slack auth token"
    required: true
  slack-channel:
    description: "Slack channel ID to post CHANGELOG to"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
